# Generated by Django 3.1.4 on 2020-12-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='poster',
            name='has_frames',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
