# Generated by Django 3.1.4 on 2020-12-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0002_auto_20201227_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='has_frames',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
