# Generated by Django 3.1.4 on 2020-12-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0003_auto_20201227_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='has_frames',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
